---
- hosts: myWebServers
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
      name: "{{myjavaonubuntu}}"
      state: absent
    when: ansible_os_family =="Debian"

  - name: install java on RedHat
    dnf:
      name: "{{myjavaonredhat}}"
      state: absent
    when: ansible_os_family =="RedHat"

